-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 00:48:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(100) NULL,
  `Numero telefonico` VARCHAR(45) NULL,
  `Dirección` VARCHAR(100) NULL,
  `Ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModeloChaqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModeloChaqueta` (
  `idModeloChaqueta` INT NOT NULL,
  `Temporada(Verano-Primavera, Invierno-Otoño, TodaTemporada)` VARCHAR(45) NULL,
  `Tendencia(Rock, IndieChic, Etnic, Western, Animalprint,otra)` VARCHAR(45) NULL,
  PRIMARY KEY (`idModeloChaqueta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chaqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chaqueta` (
  `idChaqueta` INT NOT NULL,
  `Número de serie` INT NULL,
  `Talla` VARCHAR(4) NULL,
  `Precio` FLOAT NULL,
  `ModeloChaqueta_idModeloChaqueta` INT NOT NULL,
  PRIMARY KEY (`idChaqueta`, `ModeloChaqueta_idModeloChaqueta`),
  UNIQUE INDEX `Número de serie_UNIQUE` (`Número de serie` ASC) VISIBLE,
  INDEX `fk_Chaqueta_ModeloChaqueta1_idx` (`ModeloChaqueta_idModeloChaqueta` ASC) VISIBLE,
  CONSTRAINT `fk_Chaqueta_ModeloChaqueta1`
    FOREIGN KEY (`ModeloChaqueta_idModeloChaqueta`)
    REFERENCES `mydb`.`ModeloChaqueta` (`idModeloChaqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `idPedidos` INT NOT NULL,
  `Fecha de pedido` DATETIME NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idPedidos`),
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Info_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info_Pedido` (
  `idInfo_Pedido` INT NOT NULL,
  `TotalPago` FLOAT NULL,
  `MediodePago` VARCHAR(45) NULL,
  `¿Envío a domicilio?` VARCHAR(2) NULL,
  `¿Retira en tienda?` VARCHAR(2) NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Chaqueta_idChaqueta` INT NOT NULL,
  PRIMARY KEY (`idInfo_Pedido`),
  INDEX `fk_Info_Pedido_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  INDEX `fk_Info_Pedido_Chaqueta1_idx` (`Chaqueta_idChaqueta` ASC) VISIBLE,
  CONSTRAINT `fk_Info_Pedido_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `mydb`.`Pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Info_Pedido_Chaqueta1`
    FOREIGN KEY (`Chaqueta_idChaqueta`)
    REFERENCES `mydb`.`Chaqueta` (`idChaqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
